routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Repository\RepositoryFactory;

Auth::routes(['verify' => true]);
Route::get('/sign_out', 'Auth\LoginController@getLogout')->name('sign_out');

//pages
Route::get('/', 'HomeController@index')->name('home');
Route::get('/how-it-works', function() { return view('pages.howitworks'); })->name('howitworks');
Route::get('/pricing', function() { return view('pages.pricing'); })->name('pricing');
Route::get('/about', function() { return view('pages.about'); })->name('about');
Route::get('/investors', function() { return view('pages.investors'); })->name('investors');
Route::get('/contact', function() { return view('pages.contact'); })->name('contact');

Route::get('/card', function() { return view('cards.buy'); });

//vendors
Route::get('/vendors', 'VendorsController@index')->name('vendors');
Route::post('/vendors', 'VendorsController@getoffer')->name('vendors_order');

//buy
Route::get('/buy', 'BuyController@index')->name('buy');
Route::post('/buy', 'BuyController@search')->name('buy_search');

//getoffers
Route::post('/getoffer', 'OrderController@index')->name('getoffer');
Route::post('/_callback', 'OrderController@callback')->name('callback');
Route::post('/investors', 'OrderController@investors')->name('investors_post');
Route::post('/email_subscribe', 'SubscribeController@index')->name('email_subscribe');

//sell steps
//step1
Route::post('/correct-address', 'SearchController@step1')->name('correct_address');
Route::get('/correct-address', 'SearchController@step1show')->name('correct_address_show');

//step2
Route::post('/offer-me', 'SearchController@step2')->name('offer_me');
Route::get('/offer-me', 'SearchController@step2show')->name('offer_me_show');


//other
Route::get('/search', 'SearchController@showSearch');
Route::post('/search', 'SearchController@execSearch')->name('search-results');

//cabinet
Route::group([
    'middleware' => ['auth'],
    'namespace' => 'Cabinet',
    'prefix' => 'myaccount',
    'as' => 'cabinet.'
], function() {
    Route::get('/', 'DashboardController@index')->name('home');
    Route::get('/settings', 'SettingsController@index')->name('settings');
    Route::post('/settings/change_password', 'SettingsController@change_password')->name('change_password');

    Route::get('/{house}', 'HouseController@index')->name('house_id');
});

app/Http/Controllers/Cabinet/DashboardController.php
<?php

namespace App\Http\Controllers\Cabinet;

use App\Model\Sells;
use App\Repository\RepositoryFactory;
use App\Traits\EstimateFormat;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;

class DashboardController extends Controller
{
    use EstimateFormat;

    public function index(Request $request) {
        $user = Auth::user();
        $get_houses = Sells::where('user_id',$user->id)->get();
        $houses = [];
        foreach($get_houses as $house) {
            $repository = RepositoryFactory::getRepository(RepositoryFactory::ZILLOW);
            $address = explode(',',$house->address)[0];
            $property = $repository->getProperty($address, null, null, $house->zip);

            if (! $property) {
                $houses[] = [
                    'address' => $address,
                ];
                continue;
            }

            //dd($property);
            $tempHouse = [
                'address' => $address,
                'lat' => (float) $property->latitude(),
                'lng' => (float) $property->longitude(),
                'bathrooms' => (float) $property->bathroomsCount(),
                'sqr' => (float) $property->areaSize(),
                'bedrooms' => (float) $property->bedroomsCount(),
                'zestimate' => $property->estimatedPrice(),
                'imgs' => $property->images(),
                'alias' => $house->alias
            ];

            if( $estimatedPrice = $property->estimatedPrice() ) $tempHouse['prices'] = $this->formatEstimate($estimatedPrice);

            $houses[] = $tempHouse;
        }
        return view('cabinet.index',compact('houses'));
    }
}

app/Http/Controllers/Cabinet/HouseController.php
<?php

namespace App\Http\Controllers\Cabinet;

use App\Model\Sells;
use App\Repository\RepositoryFactory;
use App\Http\Controllers\Controller;
use App\Traits\EstimateFormat;
use Illuminate\Support\Facades\Auth;

class HouseController extends Controller
{
    use EstimateFormat;

    public function index($house) {
        $house_in = Sells::where('user_id', Auth::user()->id)
                            ->where('alias','like', "%$house%")->first();

        //TODO page with 404
        if(!$house_in) return redirect(404);

        //TODO get info from Zillow
        $repository = RepositoryFactory::getRepository(RepositoryFactory::ZILLOW);
        $address = explode(',',$house_in->address)[0];
        $property = $repository->getProperty($address, null, null, $house_in->zip);

        $house = [
            'address' => $house_in->address,
            'lat' => (float) $property->latitude(),
            'lng' => (float) $property->longitude(),
            'bathrooms' => (float) $property->bathroomsCount(),
            'sqr' => (float) $property->areaSize(),
            'bedrooms' => (float) $property->bedroomsCount(),
            'imgs' => $property->images(),
            'alias' => $house_in->alias,
            'descr' => $property->descr(),
            'lastSoldPrice' => $property->lastSoldPrice(),
        ];

        if( $estimatedPrice = $property->estimatedPrice() ) $house['prices'] = $this->formatEstimate($estimatedPrice);

        $google_key = config('services.google.key');
        return view('cabinet.card', compact('house', 'property','google_key'));
    }
}

app/Http/Controllers/Cabinet/SettingsController.php
<?php

namespace App\Http\Controllers\Cabinet;

use App\Http\Requests\ChangePasswordRequest;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Auth;

class SettingsController extends Controller
{
    public function index() {
        return view('cabinet.settings.index');
    }

    public function change_password(ChangePasswordRequest $request) {
        $user = Auth::user();
        $user->password = Hash::make( $request->password );
        return back()->with([
            'success' => __('settings.change_password.success')
        ]);
    }
}

resources/views/cabinet/card.blade.php
@extends('layouts.cabinet')
@section('title', "$house[address] | ".env('APP_NAME'))
@section('description', "description")
@section('content')
    <section class="card_main">
        <div class="container">
            <div class="row">
                <div class="col-12 col-lg-9">
                    <div class="card_main_info">
                        <div class="card-carusel owl-carousel">
                            @forelse($house['imgs'] as $img)
                                <div class="card-carusel-item">
                                    <img class="card-carusel-img" src="{{ $img }}" alt="">
                                </div>
                            @empty
                                <img class="card-carusel-img" src="https://via.placeholder.com/825x500?text=iBuyershop" alt="">
                            @endforelse
                        </div>
                    </div>
                </div>
                <div class="col-12 col-lg-3">
                    <div class="card_info">
                        <h2>{{ $house['address'] }}</h2>
                        <div class="card_info_spec">
                            <div class="card_info_spec__info">
                                <p class="card_info_option">
                                    <span class="icon"><i class="flaticon-bed"></i></span>  {{ $house['bedrooms'] }} Bed
                                </p>
                                <p class="card_info_option">
                                    <span class="icon"><i class="flaticon-bathtub"></i></span> {{ $house['bathrooms'] }} Bath
                                </p>
                            </div>
                            <div class="card_info_spec__info">
                                <p class="card_info_option">{{ $house['sqr'] }} sqft</p>
                                <p class="card_info_option">$170 / Sq. Ft.</p>
                            </div>
                        </div>
                        <hr>
                        @if(isset($house['lastSoldPrice']))
                            <p class="card_info_option">
                                Last Sold Price: ${{ number_format($house['lastSoldPrice']) }}
                            </p>
                        @endif
                        @if(isset($house['prices']))
                            <h3>Estimate range:</h3>
                            <p class="card_info_option_range"><b class="blue">${{ $house['prices']['min'] }}</b> - <b class="blue">${{ $house['prices']['max'] }}</b></p>
                            <p class="card_info_option_min">Final offer will be calculated after home inspection.</p>
                        @else
                            <h3>Calculation pending</h3>
                        @endif


                        <div class="card_info_offer">
                            <p class="card_info_offer--title">Want sell? We can help you make it easer.</p>
                            <a href="#" class="btn">Click EaseSell</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section class="card_about">
        <div class="container">
            <div class="row">
                <div class="col-12 col-lg-9">
                    <div class="card_about_wrapper">

                        <div class="card_about_facts">
                            <h2>Facts and Features</h2>
                            <div class="card_about_facts_item">
                                <i class="flaticon-bathtub"></i>
                                <div class="card_about_facts_item--text">
                                    <p class="card_about_facts_item--title">Type</p>
                                    <p class="card_about_facts_item--text">Single Family</p>
                                </div>
                            </div>

                            <div class="card_about_facts_item">
                                <i class="flaticon-bathtub"></i>
                                <div class="card_about_facts_item--text">
                                    <p class="card_about_facts_item--title">Type</p>
                                    <p class="card_about_facts_item--text">Single Family</p>
                                </div>
                            </div>

                            <div class="card_about_facts_item">
                                <i class="flaticon-bathtub"></i>
                                <div class="card_about_facts_item--text">
                                    <p class="card_about_facts_item--title">Type</p>
                                    <p class="card_about_facts_item--text">Single Family</p>
                                </div>
                            </div>

                            <div class="card_about_facts_item">
                                <i class="flaticon-bathtub"></i>
                                <div class="card_about_facts_item--text">
                                    <p class="card_about_facts_item--title">Type</p>
                                    <p class="card_about_facts_item--text">Single Family</p>
                                </div>
                            </div>

                            <div class="card_about_facts_item">
                                <i class="flaticon-bathtub"></i>
                                <div class="card_about_facts_item--text">
                                    <p class="card_about_facts_item--title">Type</p>
                                    <p class="card_about_facts_item--text">Single Family</p>
                                </div>
                            </div>

                            <div class="card_about_facts_item">
                                <i class="flaticon-bathtub"></i>
                                <div class="card_about_facts_item--text">
                                    <p class="card_about_facts_item--title">Type</p>
                                    <p class="card_about_facts_item--text">Single Family</p>
                                </div>
                            </div>
                        </div>
                        <!-- /facts -->

                        <div class="card_map">
                            <div id="map"></div>
                        </div>

                        @if(isset($house['descr']))
                            <div class="card_about">
                                <p class="card_about--title">About This Home</p>
                                <p class="card_about--descr">{{ $house['descr'] }}</p>
                            </div>
                        @endif
                        <div class="card_history">
                            <p class="card_about--title">Property History for 1184 SW Ocean Dr</p>
                            <div class="card_history_table">
                                <div class="card_history_table--row caption">
                                    <div class="card_history_table--1">Date</div>
                                    <div class="card_history_table--2">Event</div>
                                    <div class="card_history_table--3">Price</div>
                                </div>
                                <div class="card_history_table--row">
                                    <div class="card_history_table--1">Nov 22, 2002</div>
                                    <div class="card_history_table--2">Sold (Public Records)</div>
                                    <div class="card_history_table--3">$130,000</div>
                                </div>
                                <div class="card_history_table--row">
                                    <div class="card_history_table--1">Apr 1, 2019</div>
                                    <div class="card_history_table--2">Sold (Public Records)</div>
                                    <div class="card_history_table--3">$230,000</div>
                                </div>
                            </div>
                        </div>

                        <div class="card_chart_price">
                            <canvas id="chart1"></canvas>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- scripts -->
    <script>
        function initMap() {
            var mapSign = {lat: {{ $house['lat'] }}, lng: {{ $house['lng'] }}};
            var map = new google.maps.Map(document.getElementById('map'), {
                zoom: 17,
                center: mapSign
            });
            var marker = new google.maps.Marker({
                position: mapSign,
                map: map
            });
        }
    </script>
    <script async defer
            src="https://maps.googleapis.com/maps/api/js?key={{ $google_key }}&callback=initMap">
    </script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.18.1/moment.min.js"></script>
    <script src="https://www.chartjs.org/dist/2.8.0/Chart.min.js"></script>
    <script>
        window.chartColors = {
            red: 'rgb(255, 99, 132)',
            orange: 'rgb(255, 159, 64)',
            yellow: 'rgb(255, 205, 86)',
            green: 'rgb(75, 192, 192)',
            blue: 'rgb(54, 162, 235)',
            purple: 'rgb(153, 102, 255)',
            grey: 'rgb(201, 203, 207)'
        };

        function randomNumber(min, max) {
            return Math.random() * (max - min) + min;
        }

        function randomBar(date, lastClose) {
            var open = randomNumber(lastClose * 0.95, lastClose * 1.05).toFixed(2);
            var close = randomNumber(open * 0.95, open * 1.05).toFixed(2);
            return {
                t: date.valueOf(),
                y: close
            };
        }

        var dateFormat = 'MMMM DD YYYY';
        var date = moment('April 01 2017', dateFormat);
        var data = [randomBar(date, 30)];
        while (data.length < 60) {
            date = date.clone().add(1, 'd');
            if (date.isoWeekday() <= 5) {
                data.push(randomBar(date, data[data.length - 1].y));
            }
        }
        var ctx = document.getElementById('chart1').getContext('2d');

        var color = Chart.helpers.color;
        var cfg = {
            type: 'bar',
            data: {
                datasets: [{
                    label: 'CHRT - Chart.js Corporation',
                    backgroundColor: color('#0099ff').alpha(0.5).rgbString(),
                    borderColor: '#0099ff',
                    data: data,
                    type: 'bar',
                    pointRadius: 0,
                    fill: false,
                    lineTension: 0,
                    borderWidth: 2
                }]
            },
            options: {
                scales: {
                    xAxes: [{
                        type: 'time',
                        distribution: 'series',
                        ticks: {
                            source: 'data',
                            autoSkip: true
                        }
                    }],
                    yAxes: [{
                        scaleLabel: {
                            display: true,
                            labelString: 'Closing price ($)'
                        }
                    }]
                },
                tooltips: {
                    intersect: false,
                    mode: 'index',
                    callbacks: {
                        label: function(tooltipItem, myData) {
                            var label = myData.datasets[tooltipItem.datasetIndex].label || '';
                            if (label) {
                                label += ': ';
                            }
                            label += parseFloat(tooltipItem.value).toFixed(2);
                            return label;
                        }
                    }
                }
            }
        };

        var chart = new Chart(ctx, cfg);
    </script>
@endsection

resources/views/cabinet/index.blade.php
@extends('layouts.cabinet')
@section('title', "Cabinet | ".env('APP_NAME'))
@section('description', "description")
@section('content')
    <section class="settings">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="section-title tal">
                        <h2 class="title">Your favorite houses</h2>
                    </div>
                </div>
            </div>
            <div class="row">
                @forelse($houses as $house)
                    <div class="col-12 col-lg-4">
                        <div class="single-funded">
                            <div class="img" style="background-image: url({{ $house['imgs'][0] ?? 'https://via.placeholder.com/400X300?text=iBuyershop' }})">
                                <span class="type">Single Family</span>
                            </div>
                            <div class="content">
                                <a href="{{ isset($house['alias']) ? route('cabinet.house_id',$house['alias']) : '#' }}" class="name">{{ $house['address'] }}</a>
                                <p class="adderss">Here is our estimate of your net proceeds.</p>
                                @if (isset($house['zestimate']))
                                    <h2 class="price_range">${{ $house['prices']['min'] }} - ${{ $house['prices']['max'] }}</h2>
                                @else
                                    <p class="status" style="margin-top: 20px;">Calculation pending...</p>
                                @endif
                            </div>
                        </div>
                    </div>
                @empty
                    <div class="col-12">
                        <p class="text">You have not registered a house for sale yet</p>
                        <a href="{{ route('home') }}" class="home1-link link hvr-bs" style="color:#fff">Start search</a>
                    </div>
                @endforelse
            </div>
        </div>
    </section>
@endsection

resources/views/cabinet/menu.blade.php
<section class="cabinet_menu">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <nav class="cabinet_menu_nav">
                    <ul>
                        <li><a href="{{ route('cabinet.home') }}" class="cabinet_menu_nav--link">Favorits</a></li>
                        <li><a href="{{ route('cabinet.settings') }}" class="cabinet_menu_nav--link">Settings</a></li>
                        <li><a href="{{ route('sign_out') }}" class="cabinet_menu_nav--link">Sign Out</a></li>
                    </ul>
                </nav>
            </div>
        </div>
    </div>
</section>