routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Repository\RepositoryFactory;

Auth::routes(['verify' => true]);
Route::get('/sign_out', 'Auth\LoginController@getLogout')->name('sign_out');

//pages
Route::get('/', 'HomeController@index')->name('home');
Route::get('/how-it-works', function() { return view('pages.howitworks'); })->name('howitworks');
Route::get('/pricing', function() { return view('pages.pricing'); })->name('pricing');
Route::get('/about', function() { return view('pages.about'); })->name('about');
Route::get('/investors', function() { return view('pages.investors'); })->name('investors');
Route::get('/contact', function() { return view('pages.contact'); })->name('contact');

Route::get('/card', function() { return view('cards.buy'); });

//vendors
Route::get('/vendors', 'VendorsController@index')->name('vendors');
Route::post('/vendors', 'VendorsController@getoffer')->name('vendors_order');

//buy
Route::get('/buy', 'BuyController@index')->name('buy');
Route::post('/buy', 'BuyController@search')->name('buy_search');

//getoffers
Route::post('/getoffer', 'OrderController@index')->name('getoffer');
Route::post('/_callback', 'OrderController@callback')->name('callback');
Route::post('/investors', 'OrderController@investors')->name('investors_post');
Route::post('/email_subscribe', 'SubscribeController@index')->name('email_subscribe');

//sell steps
//step1
Route::post('/correct-address', 'SearchController@step1')->name('correct_address');
Route::get('/correct-address', 'SearchController@step1show')->name('correct_address_show');

//step2
Route::post('/offer-me', 'SearchController@step2')->name('offer_me');
Route::get('/offer-me', 'SearchController@step2show')->name('offer_me_show');


//other
Route::get('/search', 'SearchController@showSearch');
Route::post('/search', 'SearchController@execSearch')->name('search-results');

//cabinet
Route::group([
    'middleware' => ['auth'],
    'namespace' => 'Cabinet',
    'prefix' => 'myaccount',
    'as' => 'cabinet.'
], function() {
    Route::get('/', 'DashboardController@index')->name('home');
    Route::get('/settings', 'SettingsController@index')->name('settings');
    Route::post('/settings/change_password', 'SettingsController@change_password')->name('change_password');

    Route::get('/{house}', 'HouseController@index')->name('house_id');
});

app/Http/Controllers/Cabinet/DashboardController.php
<?php

namespace App\Http\Controllers\Cabinet;

use App\Model\Sells;
use App\Repository\RepositoryFactory;
use App\Traits\EstimateFormat;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;

class DashboardController extends Controller
{
    use EstimateFormat;

    public function index(Request $request) {
        $user = Auth::user();
        $get_houses = Sells::where('user_id',$user->id)->get();
        $houses = [];
        foreach($get_houses as $house) {
            $repository = RepositoryFactory::getRepository(RepositoryFactory::ZILLOW);
            $address = explode(',',$house->address)[0];
            $property = $repository->getProperty($address, null, null, $house->zip);

            if (! $property) {
                $houses[] = [
                    'address' => $address,
                ];
                continue;
            }

            //dd($property);
            $tempHouse = [
                'address' => $address,
                'lat' => (float) $property->latitude(),
                'lng' => (float) $property->longitude(),
                'bathrooms' => (float) $property->bathroomsCount(),
                'sqr' => (float) $property->areaSize(),
                'bedrooms' => (float) $property->bedroomsCount(),
                'zestimate' => $property->estimatedPrice(),
                'imgs' => $property->images(),
                'alias' => $house->alias
            ];

            if( $estimatedPrice = $property->estimatedPrice() ) $tempHouse['prices'] = $this->formatEstimate($estimatedPrice);

            $houses[] = $tempHouse;
        }
        return view('cabinet.index',compact('houses'));
    }
}

app/Http/Controllers/Cabinet/HouseController.php
<?php

namespace App\Http\Controllers\Cabinet;

use App\Model\Sells;
use App\Repository\RepositoryFactory;
use App\Http\Controllers\Controller;
use App\Traits\EstimateFormat;
use Illuminate\Support\Facades\Auth;

class HouseController extends Controller
{
    use EstimateFormat;

    public function index($house) {
        $house_in = Sells::where('user_id', Auth::user()->id)
                            ->where('alias','like', "%$house%")->first();

        //TODO page with 404
        if(!$house_in) return redirect(404);

        //TODO get info from Zillow
        $repository = RepositoryFactory::getRepository(RepositoryFactory::ZILLOW);
        $address = explode(',',$house_in->address)[0];
        $property = $repository->getProperty($address, null, null, $house_in->zip);

        $house = [
            'address' => $house_in->address,
            'lat' => (float) $property->latitude(),
            'lng' => (float) $property->longitude(),
            'bathrooms' => (float) $property->bathroomsCount(),
            'sqr' => (float) $property->areaSize(),
            'bedrooms' => (float) $property->bedroomsCount(),
            'imgs' => $property->images(),
            'alias' => $house_in->alias,
            'descr' => $property->descr(),
            'lastSoldPrice' => $property->lastSoldPrice(),
        ];

        if( $estimatedPrice = $property->estimatedPrice() ) $house['prices'] = $this->formatEstimate($estimatedPrice);

        $google_key = config('services.google.key');
        return view('cabinet.card', compact('house', 'property','google_key'));
    }
}

app/Http/Controllers/Cabinet/SettingsController.php
<?php

namespace App\Http\Controllers\Cabinet;

use App\Http\Requests\ChangePasswordRequest;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Auth;

class SettingsController extends Controller
{
    public function index() {
        return view('cabinet.settings.index');
    }

    public function change_password(ChangePasswordRequest $request) {
        $user = Auth::user();
        $user->password = Hash::make( $request->password );
        return back()->with([
            'success' => __('settings.change_password.success')
        ]);
    }
}

resources/views/cabinet/settings/index.blade.php
@extends('layouts.cabinet')
@section('title', "Settings | ".env('APP_NAME'))
@section('description', "description")
@section('content')
    <section class="settings">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="section-title tal">
                        <h2 class="title">Settings</h2>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    <div class="settings_block">
                        <h3>Change password</h3>
                        <form action="{{ route('cabinet.change_password') }}" method="POST" class="settings_change">
                            @csrf
                            <div class="form-group">
                                <input type="password" name="password" placeholder="New password">
                                @if ($errors->has('password'))
                                    <span class="invalid-feedback" role="alert">{{ $errors->first('password') }}</span>
                                @endif
                            </div>
                            <div class="form-group">
                                <input type="password" name="password_confirmation" placeholder="Confirm New Password">
                                @if ($errors->has('password_confirmation'))
                                    <span class="invalid-feedback" role="alert">{{ $errors->first('password_confirmation') }}</span>
                                @endif
                            </div>
                            <div class="form-group">
                                <button type="submit" class="btn btn-primary">
                                    Change password
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
    @if(session('success'))
        @push('scripts')
        <script>
            showModal(1, '{{ session('success') }}');
        </script>
        @endpush
    @endif
@endsection