routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Repository\RepositoryFactory;

Auth::routes(['verify' => true]);
Route::get('/sign_out', 'Auth\LoginController@getLogout')->name('sign_out');

//pages
Route::get('/', 'HomeController@index')->name('home');
Route::get('/how-it-works', function() { return view('pages.howitworks'); })->name('howitworks');
Route::get('/pricing', function() { return view('pages.pricing'); })->name('pricing');
Route::get('/about', function() { return view('pages.about'); })->name('about');
Route::get('/investors', function() { return view('pages.investors'); })->name('investors');
Route::get('/contact', function() { return view('pages.contact'); })->name('contact');

Route::get('/card', function() { return view('cards.buy'); });

//vendors
Route::get('/vendors', 'VendorsController@index')->name('vendors');
Route::post('/vendors', 'VendorsController@getoffer')->name('vendors_order');

//buy
Route::get('/buy', 'BuyController@index')->name('buy');
Route::post('/buy', 'BuyController@search')->name('buy_search');

//getoffers
Route::post('/getoffer', 'OrderController@index')->name('getoffer');
Route::post('/_callback', 'OrderController@callback')->name('callback');
Route::post('/investors', 'OrderController@investors')->name('investors_post');
Route::post('/email_subscribe', 'SubscribeController@index')->name('email_subscribe');

//sell steps
//step1
Route::post('/correct-address', 'SearchController@step1')->name('correct_address');
Route::get('/correct-address', 'SearchController@step1show')->name('correct_address_show');

//step2
Route::post('/offer-me', 'SearchController@step2')->name('offer_me');
Route::get('/offer-me', 'SearchController@step2show')->name('offer_me_show');


//other
Route::get('/search', 'SearchController@showSearch');
Route::post('/search', 'SearchController@execSearch')->name('search-results');

//cabinet
Route::group([
    'middleware' => ['auth'],
    'namespace' => 'Cabinet',
    'prefix' => 'myaccount',
    'as' => 'cabinet.'
], function() {
    Route::get('/', 'DashboardController@index')->name('home');
    Route::get('/settings', 'SettingsController@index')->name('settings');
    Route::post('/settings/change_password', 'SettingsController@change_password')->name('change_password');

    Route::get('/{house}', 'HouseController@index')->name('house_id');
});

resources/views/layouts/app.blade.php
@include('layouts.head')
<body id="top">
<div id="preloader"></div>
@include('layouts.menu')

@yield('content')

@if(!in_array( Request::path(), ['buy'] ) )
@include('layouts.footer')
@endif

@include('layouts.scripts')
</body>
</html>

resources/views/layouts/cabinet.blade.php
@include('layouts.head')
<body id="top">
<div id="preloader"></div>
@include('layouts.menu')
@include('cabinet.menu')

@yield('content')

@if(!in_array( Request::path(), ['buy'] ) )
    @include('layouts.footer')
@endif

@include('layouts.scripts')
</body>
</html>

resources/views/layouts/footer.blade.php
<footer>
    <div class="footer-top-area">
        <div class="container">
            <div class="row">
                <div class="col-lg-2 col-md-3 col-12">
                    <div class="fw-logo footer-widget">
                        <p class="flogo"><span class="color">iBuyer</span>shop</p>
                    </div>
                </div>
                <div class="col-lg-3 col-md-5 col-sm-5 col-12">
                    <div class="fw-address footer-widget">
                        <h4 class="title">Contact Us</h4>
                        <ul class="address">
                            <li>
                                <span class="icon"><i class="flaticon-facebook-placeholder-for-locate-places-on-maps"></i></span>
                                {{ config('contacs.address') }}
                            </li>
                            <li>
                                <span class="icon"><i class="flaticon-envelope"></i></span>
                                <a href="mailto:{{ config('contacs.mail.info') }}">{{ config('contacs.mail.info') }}</a></li>
                            <li>
                                <span class="icon"><i class="flaticon-phone-receiver"></i></span>
                                <a href="tel:{{ config('contacs.phone.full') }}">{{ config('contacs.phone.format') }}</a>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-2 offset-lg-1 col-md-3 offset-md-1 col-sm-4 col-12">
                    <div class="fw-links footer-widget">
                        <h4 class="title">Quick Links</h4>
                        <ul class="links">
                            <li><a href="{{ route('home') }}">Sell</a></li>
                            <li><a href="{{ route('buy') }}">Buy</a></li>
                            <li><a href="{{ route('howitworks') }}">How it works</a></li>
                            <li><a href="{{ route('pricing') }}">Pricing</a></li>
                            <li><a href="{{ route('about') }}">About us</a></li>
                            <li><a href="{{ route('investors')  }}">Investors</a></li>
                            <li><a href="{{ route('vendors')  }}">Vendors</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-4 col-md-6 col-sm-8 col-12">
                    <div class="fw-subscribe footer-widget">
                        <h4 class="title">Stay in touch</h4>
                        <div class="fw-subscribe-input-box">
                            <form method="POST" action="{{ route('email_subscribe') }}">
                                @csrf
                                <input name="email" type="email" placeholder="Enter Email Address" required>
                                @if ($errors->has('email'))
                                    <span class="invalid-feedback" role="alert">{{ $errors->first('email') }}</span>
                                @endif
                                <button type="submit"><i class="fab fa-telegram-plane"></i></button>
                            </form>
                        </div>
                        <h4 class="title">Folllow</h4>
                        <ul class="social">
                            @foreach(config('contacs.social') as $social)
                            <li><a href="{{ $social['link'] }}" target="_blank"><i class="fab {{ $social['icon'] }}"></i></a></li>
                            @endforeach
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="footer-bottom-area">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 col-md-6 col-sm-8 col-12">
                    <p class="copyright">© iBuyershop 2019. AL Rights Reserved.</p>
                </div>
                <div class="col-lg-6 col-md-6 col-sm-4 col-12">
                    <p class="top">
                        <a href="#top" class="link smoothscroll">Back on Top <span class="icon"><i class="fas fa-chevron-up"></i></span></a>
                    </p>
                </div>
            </div>
        </div>
    </div>
</footer>

resources/views/layouts/head.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <!--- Basic Page Needs  -->
    <meta charset="utf-8">
    <base href="{{ url('/') }}">
    <title>@yield('title')</title>
    <meta name="description" content="@yield('description')">
    <meta name="author" content="">
    <meta name="keywords" content="">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Mobile Specific Meta  -->
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <meta name="yandex-verification" content="4e52abdc4afd0113" />

    <!-- CSS -->
    <link rel="stylesheet" href="{{ asset('css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ asset('css/jquery-ui.css') }}">
    <link rel="stylesheet" href="{{ asset('flaticon/flaticon.css') }}">
    <link rel="stylesheet" href="{{ asset('css/fontawesome-all.min.css') }}">
    <link rel="stylesheet" href="{{ asset('css/owl.carousel.min.css') }}">
    <link rel="stylesheet" href="{{ asset('css/animate.css') }}">
    <link rel="stylesheet" href="{{ asset('css/meanmenu.css') }}">
    <link rel="stylesheet" href="{{ asset('css/magnific-popup.css') }}">
    <link rel="stylesheet" href="{{ asset('css/style.css') }}?{{ time() }}">
    <link rel="stylesheet" href="{{ asset('css/responsive.css') }}?{{ time() }}">
    <!-- Favicon -->
    <link rel="shortcut icon" type="image/png" href="img/favicon.ico">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

    @include('layouts.icons')

    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-139100713-1"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', 'UA-139100713-1');
    </script>

    <!-- Yandex.Metrika counter -->
    <script type="text/javascript" >
        (function(m,e,t,r,i,k,a){m[i]=m[i]||function(){(m[i].a=m[i].a||[]).push(arguments)};
            m[i].l=1*new Date();k=e.createElement(t),a=e.getElementsByTagName(t)[0],k.async=1,k.src=r,a.parentNode.insertBefore(k,a)})
        (window, document, "script", "https://mc.yandex.ru/metrika/tag.js", "ym");

        ym(53443903, "init", {
            clickmap:true,
            trackLinks:true,
            accurateTrackBounce:true,
            webvisor:true
        });
    </script>
    <noscript><div><img src="https://mc.yandex.ru/watch/53443903" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
    <!-- /Yandex.Metrika counter -->
</head>

resources/views/layouts/icons.blade.php
<link rel="apple-touch-icon" sizes="180x180" href="{{ asset('/icons/apple-touch-icon.png')}}">
<link rel="icon" type="image/png" sizes="32x32" href="{{ asset('/icons/favicon-32x32.png')}}">
<link rel="icon" type="image/png" sizes="16x16" href="{{ asset('/icons/favicon-16x16.png')}}">
<link rel="manifest" href="{{ asset('/icons/site.webmanifest')}}">
<link rel="mask-icon" href="{{ asset('/icons/safari-pinned-tab.svg')}}" color="#5bbad5">
<meta name="apple-mobile-web-app-title" content="iBuyershop">
<meta name="application-name" content="iBuyershop">
<meta name="msapplication-TileColor" content="#00aba9">
<meta name="msapplication-TileImage" content="{{ asset('/icons/mstile-144x144.png')}}">
<meta name="theme-color" content="#ffffff">

resources/views/layouts/menu.blade.php
<header class="header-2" >
    <div class="@if(in_array( Request::path(), ['buy'] )) container-fluid @else container @endif">
        <div class="row">
            <div class="col-lg-2 col-12">
                <div class="logo">
                    <a class="logo-link menu-item" href="{{ route('home') }}"><span class="color">iBuyer</span>shop</a>
                    <a class="logo_phone menu-item" href="tel:{{config('contacs.phone.full')}}"><span class="flaticon-phone-receiver"></span> {{config('contacs.phone.format')}}</a>
                </div>
            </div>
            <div class="col-lg-10 col-12">
                <div class="menu">
                    <nav id="mobile_menu_active">
                        <ul>
                            <li><a href="{{ route('home') }}" class="menu-item menu_list_a">Sell</a></li>
                            <li><a href="{{ route('buy') }}" class="menu-item menu_list_a">Buy</a></li>
                            <li><a href="{{ route('howitworks') }}" class="menu-item menu_list_a">How it works</a></li>
                            <li><a href="{{ route('pricing') }}" class="menu-item menu_list_a">Pricing</a></li>
                            <li><a href="{{ route('about') }}" class="menu-item menu_list_a">About us</a></li>
                            <li><a class="" href="#">
                                    <svg style="width: 5px" version="1.1" id="Слой_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
                                         viewBox="0 0 85 301" style="enable-background:new 0 0 85 301;" xml:space="preserve">
                                            <style type="text/css">
                                                .st0{fill:#223c55;}
                                            </style>
                                        <g>
                                            <g>
                                                <circle class="st0" cx="42.5" cy="42.5" r="32"/>
                                            </g>
                                            <g>
                                                <circle class="st0" cx="42.5" cy="150.5" r="32"/>
                                            </g>
                                            <g>
                                                <circle class="st0" cx="42.5" cy="258.5" r="32"/>
                                            </g>
                                        </g>
                                    </svg>
                                </a>
                                <ul class="drop">
                                    <li><a href="{{ route('investors') }}" class="menu-item menu_list_a">Investors</a></li>
                                    <li><a href="{{ route('vendors') }}" class="menu-item menu_list_a">Vendors</a></li>
                                    <li><a href="{{ route('contact') }}" class="menu-item menu_list_a">Contact</a></li>
                                    <!-- <li><a href="#" class="menu-item menu_list_a">FAQ</a></li> -->
                                </ul>
                            </li>
                        </ul>
                        @guest
                            <a class="js-sign-item button button-reverce outline home1-link link" href="{{ route('login') }}">Sign in</a>
                            <a class="js-sign-item button  home1-link link hvr-bs" href="{{ route('register') }}">Sign up</a>
                        @else
                            <div class="cabinet_button js-sign-item">
                                <i class="fas fa-user"></i>
                                <p>{{ Auth::user()->email }}</p>
                                <ul class="drop">
                                    <li><a href="{{ route('cabinet.home') }}" class="menu-item menu_list_a">Favorits</a></li>
                                    <li><a href="{{ route('cabinet.settings') }}" class="menu-item menu_list_a">Settings</a></li>
                                    <li><a href="{{ route('sign_out') }}" class="menu-item menu_list_a">Exit</a></li>
                                </ul>
                            </div>
                        @endguest
                    </nav>
                </div>
            </div>
        </div>
    </div>
</header>

resources/views/layouts/scripts.blade.php
<!-- Scripts -->
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@8"></script>
<script src="{{ asset('js/jquery-3.3.1.min.js') }}"></script>
<script src="{{ asset('js/jquery-ui.js') }}"></script>
<script src="{{ asset('js/owl.carousel.min.js') }}"></script>
<script src="{{ asset('js/jquery.counterup.min.js') }}"></script>
<script src="{{ asset('js/jquery.meanmenu.js') }}"></script>
<script src="{{ asset('js/jquery.mixitup.min.js') }}"></script>
<script src="{{ asset('js/jquery.waypoints.min.js') }}"></script>
<script src="{{ asset('js/jquery.magnific-popup.min.js') }}"></script>
<script src="{{ asset('js/popper.min.js') }}"></script>
<script src="{{ asset('js/wow.min.js') }}"></script>
<script src="{{ asset('js/bootstrap.min.js') }}"></script>
<script src="{{ asset('js/theme.js') }}?{{ time() }}"></script>

@stack('scripts')